### PR TITLE
Page level styling

### PR DESCRIPTION
**Pull request by jtomeck**
Begin building a better structure to the different views (ie. workspace/table/node/graph detail pages). Currently this only includes the workspace detail page.

To do:
- [x] Refactor various blocks into separate components
- [ ] ~Build solution to forms~
- [ ] ~Get girder web component for multiple file upload installed~
- [ ] ~Build the rest of the views (which should be easy once one view is complete)~

UPDATE(waxlamp): I created #91 and #92 for TODO items 2 and 3 above, and TODO 4 can be taken care of view-by-view in separate PRs.

### CODE REVIEW

**Comment by waxlamp** [comment]
I can work on the refactoring.

What do you mean by "build solution to forms"?

As for GWC for multifile upload, and building the rest of the views, I think we should just handle those things one-by-one in follow-on PRs. What do you think?

**Comment by jtomeck** [comment]
> What do you mean by "build solution to forms"?

Just that I haven't made any decisions on what I want to do. ie. bury them behind a button that toggles a modal, or have them served to you up front, etc.

> As for GWC for multifile upload, and building the rest of the views, I think we should just handle those things one-by-one in follow-on PRs. What do you think?

I think I agree, but the multi-file upload component would effect how I build/style the form in general so it might be good to have at least this one moving forward? What are your thoughts?

**Comment by waxlamp** [comment]
@jtomeck take a look at my refactoring and let me know what you think.

**Comment by jtomeck** [comment]
> one-by-one in follow-on PRs

@waxlamp I know you were only talking about one specific thing, but I wanted to ask if you want that for the other views as well. My plan was to take care of most of the styling of the rest of the views in this PR, but it might make sense to split them out into multiple.

**Pull request merged**
